// src/pages/about.tsx
import React from 'react';

import data from "../data/about.json";

import Section from "../components/section";
import Paragraph from "../components/paragraph";
import List from "../components/list";

const About: React.SFC<{}> = () => (
  <Section id="about" title={data.title}>
    <Paragraph text={data.text} />
    <List items={data.tech} columns={2} />
  </Section>
);

export default About;

// src/components/sections/About.svelte
<script>
  import Section from '../base/Section.svelte'
  import Paragraph from '../base/Paragraph.svelte'
  import List from '../base/List.svelte'

  import data from '../../data/about.json'
</script>

<Section id="about" title="About">
  <Paragraph>
    {#each data.text as paragraph}
      <p>{paragraph}</p>
    {/each}
  </Paragraph>

  <List columns={2} items={data.tech} />
</Section>
