// src/pages/contact.tsx
import React from 'react'

import data from '../data/contact.json'

import Section from '../components/section'
import Paragraph from '../components/paragraph'
import List from '../components/list'

import styles from "../styles/contact.module.css";

const Contact: React.SFC<{}> = () => (
  <Section id="contact" title={data.title}>
    <Paragraph text={data.text} />
    <List items={data.opinions} className={styles.opinions} />
    <Paragraph text={data.closingText} className={styles.closingText} />
  </Section>
)

export default Contact

// src/components/sections/Contact.svelte
<script>
  import Section from '../base/Section.svelte'
  import Paragraph from '../base/Paragraph.svelte'
  import List from '../base/List.svelte'

  import data from '../../data/contact.json'
</script>

<style>
  .opinions {
    margin-top: 20px;
  }
</style>

<Section id="contact" title="Contact">
  <div class="opinions">
    <Paragraph>
      {#each data.text as line}
        <p>
          {@html line}
        </p>
      {/each}
    </Paragraph>
  </div>

  <List items={data.opinions} />
</Section>
