// src/pages/About.svelte
<script>
  import Page from 'components/Page.svelte'
  import Paragraph from 'components/Paragraph.svelte'
  import List from 'components/List.svelte'

  import data from 'data/about.json'
</script>

<Page id="about" title="About">
  <Paragraph>
    {#each data.text as paragraph}
      <p>{paragraph}</p>
    {/each}
  </Paragraph>

  <List columns={2} items={data.tech} />
</Page>

// src/pages/about.tsx
import React from 'react';

import data from "../data/about.json";

import Section from "../components/section";
import Paragraph from "../components/paragraph";
import List from "../components/list";

const About: React.SFC<{}> = () => (
  <Section id="about" title={data.title}>
    <Paragraph text={data.text} />
    <List items={data.tech} columns={2} />
  </Section>
);

export default About;
