// src/pages/contact.tsx
import React from 'react'

import data from '../data/contact.json'

import Section from '../components/section'
import Paragraph from '../components/paragraph'
import List from '../components/list'

import styles from "../styles/contact.module.css";

const Contact: React.SFC<{}> = () => (
  <Section id="contact" title={data.title}>
    <Paragraph text={data.text} />
    <List items={data.opinions} className={styles.opinions} />
    <Paragraph text={data.closingText} className={styles.closingText} />
  </Section>
)

export default Contact

// src/pages/Contact.svelte
<script>
  import Page from 'components/Page.svelte'
  import Paragraph from 'components/Paragraph.svelte'
  import List from 'components/List.svelte'

  import data from 'data/contact.json'
</script>

<style>
  .opinions {
    margin-top: 20px;
  }

  .closingText {
    width: 100%;
    margin-top: 40px;
  }
</style>

<Page id="contact" title="Contact">
  <Paragraph>
    {#each data.text as line}
      <p>{line}</p>
    {/each}
  </Paragraph>

  <List items={data.opinions} />
</Page>
