// src/components/footer.tsx
import React from 'react'
import { StaticQuery, graphql } from 'gatsby'
import map from "lodash/map";

import styles from '../styles/footer.module.css'

import github from '../images/icons/github.svg'
import medium from '../images/icons/medium.svg'
import dribbble from '../images/icons/dribbble.svg'
import behance from '../images/icons/behance.svg'
import angellist from '../images/icons/angellist.svg'
import linkedin from "../images/icons/linkedin.svg";

const links = [
  {
    id: 'github',
    icon: github,
    url: 'https://github.com/madebysid',
  },
  {
    id: 'medium',
    icon: medium,
    url: 'https://medium.com/@madebysid',
  },
  {
    id: 'dribbble',
    icon: dribbble,
    url: 'https://dribbble.com/madebysid',
  },
  {
    id: 'behance',
    icon: behance,
    url: 'https://www.behance.net/madebysid',
  },
  {
    id: 'angellist',
    icon: angellist,
    url: 'https://angel.co/siddhantsinha',
  },
  {
    id: 'linkedin',
    icon: linkedin,
    url: 'https://www.linkedin.com/in/madebysid',
  },
]

const Footer = () => (
  <div className={styles.container}>
    {map(links, link => (
      <a
        href={link.url}
        target="_blank"
        rel="noreferrer noopener"
        className={styles.link}
        key={link.id}
      >
        <img src={link.icon} className={styles.icon} />
      </a>
    ))}
  </div>
)

export default Footer

// src/components/Footer.svelte
<script>
  import Icon from 'components/Icon.svelte'

  const links = [
    {
      icon: 'github',
      url: 'https://github.com/madebysid'
    },
    {
      icon: 'angelList',
      url: 'https://angel.co/siddhantsinha'
    },
    {
      icon: 'linkedIn',
      url: 'https://www.linkedin.com/in/madebysid'
    }
  ]
</script>

<style>
  .container {
    display: flex;
    flex-direction: column;
    position: fixed;
    right: 50px;
    bottom: 20px;
    width: 38px;
  }

  .link {
    padding: 10px;
  }

  .link:hover {
    fill: #ea5455;
  }

  @media (max-width: 650px) {
    .container {
      flex-direction: row;
      position: absolute;
      top: 80px;
      left: 0;
      right: 0;
      margin: 0 auto;
      width: 230px;
    }
  }
</style>

<div class="container">
  {#each links as link}
    <a class="link" href={link.url} target="_blank" rel="noreferrer nooponer">
      <Icon type={link.icon} />
    </a>
  {/each}
</div>
