// src/components/header.tsx
import React from 'react'
import { Link } from 'gatsby';
import { Trail } from "react-spring";

import styles from "../styles/header.module.css";

type HeaderLink = {
  id: string
  label: string
  url: string
  external?: boolean
  highlight?: true
};

const links: HeaderLink[] = [{
  id: 'about',
  label: 'About',
  url: '#about'
}, {
  id: 'experience',
  label: 'Experience',
  url: '#experience'
}, {
  id: 'projects',
  label: 'Projects',
  url: '#projects'
}, {
  id: 'resume',
  label: 'Resume',
  url: 'https://goo.gl/P6eL5k',
  external: true,
  highlight: true
}];

const Header: React.SFC<{}> = () => (
  <div className={styles.container}>
    <Trail
      items={links}
      keys={link => link.id}
      from={{ transform: 'translateY(-40px)' }}
      to={{ transform: 'translateY(0px)' }}
    >
      {(link: HeaderLink) => props => {
        if (link.external) {
          return (
            <a
              style={props}
              className={styles.linkExternal}
              href={link.url}
              target="_blank"
              rel="noreferrer noopener"
            >
              {link.label}
            </a>
          ) 
        }

        return (
          <Link
            style={props}
            className={styles.link}
            activeClassName={styles.active}
            to={link.url}
          >
            {link.label}
          </Link>
        ) 
      }}
    </Trail>
  </div>
)

export default Header;

// src/components/Header.svelte
<script>
  const links = [
    {
      label: 'About',
      url: '#about'
    },
    {
      label: 'Experience',
      url: '#experience'
    },
    {
      label: 'Projects',
      url: '#projects'
    }
  ]
</script>

<style>
  .container {
    display: flex;
    justify-content: flex-end;
    align-self: flex-end;
    padding-top: 20px;
    margin-right: 50px;
    flex: 0 0 30px;
  }

  .link {
    color: #a1adbd;
    text-decoration: none;
    margin: 0 20px;
    font-size: 14px;
    position: relative;
  }

  .link--highlight {
    color: #ea5455;
  }

  @keyframes slide {
    from {
      width: 0;
    }

    to {
      width: 100%;
    }
  }

  .link:hover:after {
    content: '';
    animation: slide 0.5s forwards;
    height: 2px;
    position: absolute;
    left: 0;
    top: 24px;
    background-color: #ea5455;
  }

  .link.active {
    font-weight: 700;
    color: #ea5455;
  }
</style>

<div class="container">
  {#each links as link}
    <a class="link" href={link.url}>{link.label}</a>
  {/each}

  <a
    class="link link--highlight"
    href="https://goo.gl/P6eL5k"
    target="_blank"
    rel="noreferrer noopener">
    Resume
  </a>
</div>
